### ISSUE TITLE
XP_CI_AudioVibro

### ISSUE THREAD

**Issue by cedlenoir** [cedlenoir/XP_CI_Audio_Vibro#2]
We need to:
- change the parameters (stimuli, volume, trigger, session name) depending on the modality
- generate EEG-BIDS related files
- update the number of trials
- update the number of sessions to 2 (vibro and audio)

**Comment by cedlenoir** [comment]
generate EEG-BIDS related files:
In the scripts I have from Tomáš not all EEG-BIDS related files are created and complete + it is not that clean to add all the bids related scripts in the main XP script + we need different versions for the EEG files and the tapping files 
therefore I suggest that for pilot and first tests we skip EEG-BIDS formating...?

**Comment by cedlenoir** [comment]
As you can see I change the GUIs to have one for each modality to avoid conflicts in volume and device used to play stimuli.
Small bugs fixed + added info in the log text files (stimulus used).
We are all set!

**Comment by cedlenoir** [comment]
We need to:

- add visual instruction and feedback in french for the patient (especially when the implant is off)
- display the number and position of the deviant cycles for the deviant trial
- build different low-passed stimuli (to test in the clinic with CI patients for "pleasantness" of the sound)

**Comment by florarosen** [comment]
A discuter avec Justine : 
- Profil patient a recruter pour pilot (quid âge, résultats, difficulté de la tâche etc)
- Faire écouter stimulus à un patient pour pleasentness rating
- Comment accéder aux documents pré-épic
- Liste des patients implantés sur 1 année pour données démographiques (Muriel ?) 
- Coque protection eau (gel EEG)
- Noise reduction du speech processor (possible vocoder mon stimulus pour avoir une idée ?)

**Comment by florarosen** [comment]
To do : 
- Finish script for extra instructions on screen 
- Transcript app for discussion with patients
- Sonometer to evaluate exact frequency spectrum of delivered sound
- Test vibro for sound level in air conduction + bone conduction (with ear plugs + noise cancelling headphones)

**Comment by cedlenoir** [comment]
Transcript app for discussion with patients: Word fait ça super bien, on peut dicter et écrire si besoin et le display est adaptable. En plus on puet garder une trace écrite des échanges.

Script adapté de mon côté pour les déviants, pull mes changements si tu veux modifier le script XP_CI ou on fait comme la dernière fois tu fais une branche et une PR et on fusionnera nos changements.

**Comment by cedlenoir** [comment]
Familiarization script added

For the familiarization stimuli and the others can we just do a version with a low pass filter to see how it changes the onset and ''annoying'' high pitched component?
